Movies:
  columns:
    movieId: int64
    title: string
    genres: string

MoviesRatings:
  columns:
    userId: int64
    movieId: int64
    rating: float64
    timestamp : float64

MoviesTags:
  columns:
    userId: int64
    movieId: int64
    tag: string
    timestamp: int64

MoviesLinks:
  columns:
    movieId: int64
    imdbId: int64
    tmdbId: int64
