Movies:
  columns:
    movieId: int64
    title: string
    genres: string

MoviesRatings:
  columns:
    userId: float64
    movieId: float64
    rating: float64
    timestamp : float64

MoviesTags:
  columns:
    userId: float64
    movieId: float64
    tag: object
    timestamp: int64

MoviesLinks:
  columns:
    movieId: float64
    imdbId: float64
    tmdbId: float64
