columns:
    InvoiceNo: string
    StockCode: string
    Description: string
    Quantity: int64
    InvoiceDate: datetime64[ns]
    UnitPrice: float64
    CustomerID: float64
    Country: string

numerical_columns:
  - Quantity
  - UnitPrice
  - CustomerID
